name: Collector

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@latest  # Use the latest version

    - name: Set up Go
      uses: actions/setup-go@latest  # Use the latest version
      with:
        go-version: 1.17

    - name: Fetch Telegram messages
      run: |
        go run ./fetch_telegram.go

    - name: Build and run Golang file
      run: |
        go run ./main.go

    - name: Commit Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add ./vmess_iran.txt
        git add ./trojan_iran.txt
        git add ./vless_iran.txt
        git add ./ss_iran.txt
        git add ./mixed_iran.txt
        git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected" || echo "No changes to commit"

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
